# Simple NN in python with 1 hidden layer

This NN model is a naive implementation of a Neural Network in Python and is going to be used to train and then compare and test with a few embedded platforms. The class code is taken from [here](https://github.com/llSourcell/Make_a_neural_network/blob/master/demo.py).

## Prerequisites
You need to install jupyter notebook for this example to run. The easiest way is to install miniconda and then use conda to install nupmy and jupyter.

In [14]:
import numpy as np

In [116]:
class NeuralNetwork():
    def __init__(self, training_set_inputs, training_set_outputs):
        
        self.input = training_set_inputs
        self.y = training_set_outputs
        
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        np.random.seed(1)
        # Create a 3-4-1 network
        self.weights1   = np.random.rand(self.input.shape[1],32) 
        self.weights2   = np.random.rand(32,1)

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through the hidden layer
            output = self.__sigmoid(np.dot(training_set_inputs, self.weights1))
            # 2nd layer
            output2 = self.__sigmoid(np.dot(output, self.weights2))

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output2

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.            
            d_weights2 = np.dot(output.T, (2*(self.y - output2) * self.__sigmoid_derivative(output2)))
            d_weights1 = np.dot(training_set_inputs.T,  (np.dot(2*(self.y - output2) * self.__sigmoid_derivative(output2), self.weights2.T) * self.__sigmoid_derivative(output)))

            # Adjust the weights.
            self.weights1 += d_weights1
            self.weights2 += d_weights2

    # The neural network predicts.
    def predict(self, inputs):
        output = self.__sigmoid(np.dot(inputs, self.weights1))
        # 2nd layer
        return self.__sigmoid(np.dot(output, self.weights2))


## 1. Create a labeled train set with data and labels.

Now we need to create our input data and then label them. In this case `label` just means the output, so we have two labels 0 and 1, or you can just think of these labels as binary outputs, in this case. The data are those on the next table:

D2 | D1 | D0 | Label
-|-|-|-
0 | 0 | 1 | 0
1 | 1 | 1 | 1
1 | 0 | 1 | 1
0 | 1 | 1 | 0

In Python the above table is translated to those two arrays:

In [117]:
training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = np.array([[0, 1, 1, 0]]).T

## 2. Intialise a single neuron neural network

First we need to create an `NeuralNetwork` object and initialize it. In this case initialization means that the weights will get a random value, but with using a constant seed, so the weights are re-producable per run.

In [118]:
neural_network = NeuralNetwork(training_set_inputs, training_set_outputs)

In [119]:
print("Random starting synaptic weights:")
print(neural_network.weights1)

Random starting synaptic weights:
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
  3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01
  2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01
  4.17304802e-01 5.58689828e-01 1.40386939e-01 1.98101489e-01
  8.00744569e-01 9.68261576e-01 3.13424178e-01 6.92322616e-01
  8.76389152e-01 8.94606664e-01 8.50442114e-02 3.90547832e-02
  1.69830420e-01 8.78142503e-01 9.83468338e-02 4.21107625e-01]
 [9.57889530e-01 5.33165285e-01 6.91877114e-01 3.15515631e-01
  6.86500928e-01 8.34625672e-01 1.82882773e-02 7.50144315e-01
  9.88861089e-01 7.48165654e-01 2.80443992e-01 7.89279328e-01
  1.03226007e-01 4.47893526e-01 9.08595503e-01 2.93614148e-01
  2.87775339e-01 1.30028572e-01 1.93669579e-02 6.78835533e-01
  2.11628116e-01 2.65546659e-01 4.91573159e-01 5.33625451e-02
  5.74117605e-01 1.46728575e-01 5.89305537e-01 6.99758360e-01
  1.02334429e-01 4.14055988e-01 6.9

## 3. Train the neural network. using a training set.

Now using the above training set we can train our NN. To do that we can run it 10,000 times and make small adjustments each time.

In [120]:
neural_network.train(training_set_inputs, training_set_outputs, 10000)

print("New weights_1 after training: \n")
print(neural_network.weights1)

New synaptic weights after training: 

[[ 1.5519611   1.06265208 -2.30455417  0.30877321 -1.17039621 -0.69348733
   0.40589165 -0.05932593  1.392689    0.48329391 -0.95295493  2.10166106
  -0.08448525  2.540211   -1.84539917 -0.01802026  0.92427558  1.08965851
  -1.82176436  0.45220284  2.14035487  1.82177898  0.62309348 -0.05199235
   0.29694869  0.39180283 -1.72233784 -1.70252288  0.78278019  1.28860736
  -0.47323461  1.49427898]
 [ 0.65860842  0.31949065  0.30591339  0.13609545  0.37650795  0.60220631
  -0.18831817  0.59004868  0.70259631  0.60207043  0.07404055  0.39611358
  -0.10317019  0.05323626  0.48765352  0.18219485  0.04736742 -0.0801783
  -0.20573879  0.4997675  -0.03879152 -0.11746983  0.30696019 -0.05282913
   0.54693956  0.07674308  0.36036508  0.30217376 -0.07366525  0.17580282
   0.48374213  0.191315  ]
 [-0.85158313 -0.13750623  0.7240955   0.06030529  0.68144084  0.28797794
   0.35705378 -0.1701374  -0.74218012  0.38431145  0.3302735  -1.00823685
   0.53841852 -1.063

In [123]:
print("New weights_2 after training: \n")
print(neural_network.weights2)

New weights_2 after training: 

[[ 1.45800076]
 [ 0.70967606]
 [-2.68516009]
 [ 0.02268129]
 [-1.49619033]
 [-0.91787325]
 [ 0.09344477]
 [-0.29547836]
 [ 1.28547469]
 [ 0.04046954]
 [-1.29961045]
 [ 2.02908422]
 [-0.42753493]
 [ 2.49285692]
 [-2.11993655]
 [-0.59068471]
 [ 0.62114759]
 [ 0.76446439]
 [-2.22804807]
 [ 0.25244996]
 [ 1.9591224 ]
 [ 1.53351039]
 [ 0.37624935]
 [-0.74102723]
 [-0.48484892]
 [-0.2683768 ]
 [-2.020174  ]
 [-1.99787033]
 [ 0.54688533]
 [ 0.90035289]
 [-0.67413096]
 [ 1.31408841]]


## 4. Test the trained model

Now that we have a trained NN, we can test it by passing input data that it doesn't know about.


In [121]:
# All possible inputs
inputs = np.array([
    [0,0,0],
    [0,0,1],
    [0,1,0],
    [0,1,1],
    [1,0,0],
    [1,0,1],
    [1,1,0],
    [1,1,1]])

In [122]:
for i in range(0, 8):
    print("{} = {}".format(inputs[i], neural_network.predict(inputs[i])))

[0 0 0] = [0.28424671]
[0 0 1] = [0.00297735]
[0 1 0] = [0.21864649]
[0 1 1] = [0.00229043]
[1 0 0] = [0.99992042]
[1 0 1] = [0.99799112]
[1 1 0] = [0.99988018]
[1 1 1] = [0.99720236]
